---
## Tasks needed for setup redis cluster
- name: Install fresh ruby repo
  apt_repository:
    repo: "ppa:brightbox/ruby-ng"
    state: present

- name: Install ruby 2.3
  apt:
    name: ruby2.3

- name: Install redis gem
  gem:
    name: redis
    user_install: no

- name: Install redis-trib from localfile.
  copy:
    src: redis-trib.rb
    dest: /usr/bin/redis-trib.rb
    mode: 0755

- name: Install redis-discovery from localfile.
  copy:
    src: redis-discovery.sh
    dest: /usr/bin/redis-discovery.sh
    mode: 0755

- name: Run cluster discovery script
  shell: redis-discovery.sh >> /var/log/redis-discovery.log
