---
## Tasks needed for setup redis cluster
- name: Install fresh ruby repo
  apt_repository:
    repo: "ppa:brightbox/ruby-ng"
    state: present

- name: Install ruby 2.3
  apt:
    name: ruby2.3

- name: Install redis gem
  gem:
    name: redis
    user_install: no

- name: get ec2 facts
  ec2_facts:

- name: get ec2 tags for this instance
  local_action:
    module: ec2_tag
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
    state: list
  register: ec2_tags

- name: Install redis-trib from localfile.
  copy:
    src: redis-trib.rb
    dest: /usr/bin/redis-trib.rb
    mode: 0755

- name: Install redis-discovery from localfile.
  template:
    src: scripts/redis-discovery.sh.j2
    dest: /usr/bin/redis-discovery.sh
    mode: 0755

- name: Install redis-discovery from localfile (python).
  template:
    src: scripts/redis-discovery.py.j2
    dest: /usr/bin/redis-discovery.py
    mode: 0755

- name: Run cluster discovery script
  shell: redis-discovery.py >> /var/log/redis-discovery.log
  when: redis_cluster_provisioner == 'python'

- name: Run cluster discovery script
  shell: redis-discovery.sh >> /var/log/redis-discovery.log
  when: redis_cluster_provisioner == 'bash'
