---
- name: install debian redis-tools
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - redis-tools
  when: ansible_os_family == "Debian"
